/**
 * Audio Manifest — Type Definitions  (issues #239, #244, #245 / Audio V5 v2)
 *
 * Defines the runtime-facing audio manifest that maps every generated audio
 * asset to its file path, duration, and playback metadata.  The manifest is
 * the single contract between the TTS rendering pipeline and the frontend
 * audio playback layer.
 *
 * ─── PURPOSE ──────────────────────────────────────────────────────────────────
 *
 * The render manifest (`RenderManifest` in batchRenderer.ts) is a pipeline
 * artefact — it tracks render keys and output paths to support incremental
 * re-renders.  The **audio manifest** is the runtime artefact — it is
 * consumed by the frontend to resolve AudioIds to file paths and durations
 * without requiring any pipeline state.
 *
 * ─── SCHEMA ───────────────────────────────────────────────────────────────────
 *
 *  AudioManifestEntry   Per-asset metadata:
 *    id               Stable AudioId (primary key)
 *    filePath         Relative path to the audio file served from public/
 *    hash             Render key hash (content-stable; changes when inputs change)
 *    durationMs       Clip duration in milliseconds; null when not yet measured
 *    type             Asset type (phoneme | word | prompt | …)
 *    voiceProfile     TTS voice profile identifier
 *    locale           BCP-47 locale string
 *    preloadPriority  Hint to the preloader (critical | high | normal | low)
 *    tags             Free-form categorisation tags (from inventory)
 *    generatedAt      ISO-8601 timestamp of the last successful render
 *
 *  AudioManifest   Root manifest object:
 *    manifestVersion  Schema version for forward-compatibility (issue #244)
 *    pipelineVersion  Pipeline version that generated this manifest
 *    generatedAt      ISO-8601 timestamp of manifest generation
 *    entries          Record<AudioId, AudioManifestEntry> for O(1) lookup (#245)
 *
 * ─── VERSIONING & COMPATIBILITY (issue #244) ──────────────────────────────────
 *
 * Manifest versions follow semantic versioning:
 *
 *   MAJOR  Breaking schema change — runtime must refuse incompatible manifests
 *   MINOR  Additive change       — runtime may safely ignore unknown fields
 *   PATCH  Non-schema fix        — always compatible
 *
 * The runtime should call `isManifestCompatible()` before consuming a manifest
 * to detect version mismatches early.  A mismatch means the manifest was
 * generated by a different schema version and must be regenerated.
 *
 * ─── PRELOAD PRIORITY ─────────────────────────────────────────────────────────
 *
 * Preload priorities guide the frontend preloader so that the most important
 * clips are warmed before activity start:
 *
 * | Priority  | Typical type              | When to warm                        |
 * |-----------|---------------------------|-------------------------------------|
 * | critical  | phoneme                   | Before any phonics activity loads   |
 * | high      | feedback, prompt          | At activity init                    |
 * | normal    | word                      | During activity idle time           |
 * | low       | reward, ui, narration     | Background / best-effort            |
 *
 * ─── RUNTIME LOOKUP (issue #245) ─────────────────────────────────────────────
 *
 * Entries are stored as a flat Record<string, AudioManifestEntry> keyed by
 * AudioId.  This gives O(1) lookup cost regardless of manifest size:
 *
 *   const entry = manifest.entries[audioId];
 *   if (!entry) { / handle missing / }
 *   playAudio(entry.filePath);
 *
 * ─── USAGE ────────────────────────────────────────────────────────────────────
 *
 *   import type { AudioManifest, AudioManifestEntry } from '../types/audioManifest';
 *   import { isManifestCompatible, AUDIO_MANIFEST_SCHEMA_VERSION } from '../types/audioManifest';
 *
 *   const manifest: AudioManifest = loadManifest();
 *   if (!isManifestCompatible(manifest)) {
 *     throw new Error('Manifest schema mismatch — please re-run the audio pipeline');
 *   }
 *   const entry = manifest.entries['phoneme.letter.s'];
 */

import type { AudioId } from './audioId';
import type { AudioPhraseType } from './audioPhrases';

// ─── Preload priority ─────────────────────────────────────────────────────────

/**
 * Preload hint for a single audio asset.
 *
 * Used by the frontend preloader to prioritise which clips to warm before
 * an activity starts.  Does not affect playback correctness — only load order.
 *
 * | Value      | Meaning                                                     |
 * |------------|-------------------------------------------------------------|
 * | `critical` | Must be warmed before the activity renders                  |
 * | `high`     | Should be warmed at activity initialisation                 |
 * | `normal`   | Warm during idle time (default)                             |
 * | `low`      | Background best-effort warm (rewards, UI sounds, narration) |
 */
export const PRELOAD_PRIORITIES = ['critical', 'high', 'normal', 'low'] as const;

/** Union of all valid preload priority values. */
export type PreloadPriority = (typeof PRELOAD_PRIORITIES)[number];

/**
 * Default preload priority assigned to each audio phrase type.
 *
 * Callers may override this when building manifest entries.
 */
export const PRELOAD_PRIORITY_BY_TYPE: Record<AudioPhraseType, PreloadPriority> = {
  phoneme: 'critical',
  word: 'normal',
  prompt: 'high',
  feedback: 'high',
  reward: 'low',
  ui: 'low',
  narration: 'low',
};

// ─── Per-asset manifest entry ─────────────────────────────────────────────────

/**
 * Runtime metadata for a single generated audio asset.
 *
 * This is the record the frontend reads to resolve an AudioId to a playable
 * file and to control preloading and playback timing.
 */
export interface AudioManifestEntry {
  /**
   * The stable semantic AudioId for this asset.
   * This is the primary key — equal to the key in `AudioManifest.entries`.
   */
  id: AudioId;

  /**
   * Path to the audio file relative to the project `public/` root.
   *
   * Suitable for use as a URL path in the browser:
   *   `new Audio('/' + entry.filePath)`
   *
   * Example: `"audio/phoneme_letter_s__a3f2b1c4.mp3"`
   */
  filePath: string;

  /**
   * Deterministic render key hash for this asset's inputs.
   *
   * Derived from the render key computed during the TTS pipeline run.
   * Changes whenever the TTS text, voice profile, locale, phonics metadata,
   * or pipeline version change.  Stable between runs when no inputs change.
   *
   * Can be used by the frontend cache layer to detect stale cached blobs.
   */
  hash: string;

  /**
   * Duration of the rendered clip in milliseconds.
   *
   * `null` when the duration could not be measured during rendering (e.g.
   * for dry-run outputs or when the TTS engine does not report it).
   *
   * When present, the frontend can use this value to:
   *  - Show progress bars during phoneme-sound playback
   *  - Guard against TTS-fetch delays by padding UI timing
   *  - Validate that clips are within the phonics maxDurationMs constraint
   */
  durationMs: number | null;

  /**
   * Asset type — matches `AudioPhraseEntry.type` in the inventory.
   * Used to group and filter assets in the preloader and cache eviction logic.
   */
  type: AudioPhraseType;

  /**
   * TTS voice profile identifier used to synthesise this clip.
   * Example: `'mermaid-default'`
   */
  voiceProfile: string;

  /**
   * BCP-47 locale string for this clip.
   * Example: `'en-US'`
   */
  locale: string;

  /**
   * Preload priority hint for this asset.
   * Defaults are derived from the asset type; see `PRELOAD_PRIORITY_BY_TYPE`.
   */
  preloadPriority: PreloadPriority;

  /**
   * Free-form categorisation tags copied from the inventory entry.
   * Examples: `['satpin', 'level-1', 'seashell-match']`
   */
  tags: string[];

  /**
   * ISO-8601 timestamp of the last successful render for this asset.
   */
  generatedAt: string;
}

// ─── Manifest root ────────────────────────────────────────────────────────────

/**
 * The root audio manifest object consumed by the frontend at runtime.
 *
 * Produced by `buildAudioManifest()` after a successful batch render run and
 * saved to a well-known location (e.g. `public/audio/audio-manifest.json`).
 */
export interface AudioManifest {
  /**
   * Schema version for forward-compatibility.
   *
   * Follows semantic versioning:
   *  - MAJOR: breaking shape change — runtime must refuse incompatible manifests
   *  - MINOR: additive change — runtime may safely ignore unknown fields
   *  - PATCH: non-schema fix — always compatible
   *
   * See `AUDIO_MANIFEST_SCHEMA_VERSION` for the current value and
   * `isManifestCompatible()` for the runtime check.
   */
  manifestVersion: string;

  /**
   * Pipeline version that produced this manifest.
   * Copied from `PIPELINE_VERSION` in `renderKeyGenerator.ts`.
   */
  pipelineVersion: string;

  /**
   * ISO-8601 timestamp of when this manifest was generated.
   */
  generatedAt: string;

  /**
   * Flat map of AudioId → AudioManifestEntry.
   *
   * Keyed by AudioId string for O(1) lookup:
   *   `const entry = manifest.entries[audioId]`
   *
   * Contains only assets that were successfully rendered and are currently
   * available on disk.  Failed, blocked, and stale assets are excluded.
   */
  entries: Record<string, AudioManifestEntry>;
}

// ─── Versioning & compatibility (issue #244) ──────────────────────────────────

/**
 * Current schema version for the audio manifest.
 *
 * Bump the MAJOR component for any breaking change to `AudioManifestEntry`
 * or `AudioManifest` that would prevent an existing runtime from consuming
 * the manifest correctly.
 *
 * Bump MINOR for additive, backwards-compatible additions (new optional fields).
 * Bump PATCH for non-schema corrections (documentation, tooling).
 */
export const AUDIO_MANIFEST_SCHEMA_VERSION = '1.0.0';

/**
 * Checks whether a loaded manifest is compatible with the current schema.
 *
 * Compatibility rules (issue #244):
 *  - The manifest's MAJOR version must equal the expected MAJOR version.
 *  - MINOR and PATCH differences are tolerated (additive/non-breaking).
 *
 * @param manifest         The manifest to check.
 * @param expectedVersion  The schema version to check against.
 *                         Defaults to `AUDIO_MANIFEST_SCHEMA_VERSION`.
 * @returns `true` if the manifest can be safely consumed; `false` otherwise.
 */
export function isManifestCompatible(
  manifest: Pick<AudioManifest, 'manifestVersion'>,
  expectedVersion: string = AUDIO_MANIFEST_SCHEMA_VERSION,
): boolean {
  const manifestMajor = manifest.manifestVersion.split('.')[0];
  const expectedMajor = expectedVersion.split('.')[0];
  return manifestMajor === expectedMajor;
}
